url: https://isatitech.github.io
baseurl:
# Site settings
title: Indian Students Association of Tokyo Tech
email: isatitech@gmail.com
description: "Official website of the Indian Students Association of Tokyo Tech"


# Team names, titles and social links
people:
- name: Shreya Thusoo
  pic: shreya
  position: President

- name: Rajiv Mishra
  pic: rajiv
  position: General Secretary

- name: Sameer Deshmukh
  pic: sameer
  position: Webmaster

- name: Ritesh Saini
  pic: ritesh
  position: Public Relations Officer

- name: Vigneshwaran Krishnamurthy
  pic: vignesh
  position: TISA Representative

- name: Ronit Kumar
  pic: ronit
  position: Treasurer

- name: Karthik Rampalli
  pic: kartik
  position: Cultural Event Manager, Embassy Event Manager

- name: Sindhu Sreeranga
  pic: sindhu
  position: Cultural Event Manager, Academic Event Manager

- name: Deepshikha Nair
  pic: deepshikha
  position: Embassy Event Manager

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ISATiTech
  - title: github
    url: https://github.com/isatitech

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
